{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "12550fa6_b90efe08",
        "filename": "src/sources/lustre.c",
        "patchSetId": 2
      },
      "lineNbr": 90,
      "author": {
        "id": 1019142
      },
      "writtenOn": "2022-09-12T14:15:50Z",
      "side": 1,
      "message": "question: shouldn\u0027t you pass rc or errno here to display which error occured? It seems to me that these call can fail and the error should be reported to the user (same question for the next call).",
      "range": {
        "startLine": 90,
        "startChar": 28,
        "endLine": 90,
        "endChar": 29
      },
      "revId": "af602fe54fc657a4660dfd97cdbbd6933ad7af47",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}